<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="es-ES" sourcelanguage="en">
  <context>
    <name>HtmlExport</name>
    <message>
      <location filename="../htmlexport.cpp" line="45"/>
      <source>SQL query results</source>
      <translation>Resultados de la consulta SQL</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="54"/>
      <source>Query:</source>
      <translation>Consulta:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="94"/>
      <location filename="../htmlexport.cpp" line="188"/>
      <source>no type</source>
      <translation>sin tipo</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="125"/>
      <source>Exported table: %1</source>
      <translation>Tabla exportada: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="136"/>
      <source>Exported view: %1</source>
      <translation>Vista exportada: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="157"/>
      <location filename="../htmlexport.cpp" line="280"/>
      <source>Table: %1</source>
      <translation>Tabla: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="283"/>
      <source>virtual</source>
      <translation>virtual</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="335"/>
      <source>Exported database: %1</source>
      <translation>Base de datos exportada: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="351"/>
      <source>Index: %1</source>
      <translation>Índice: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="357"/>
      <source>For table:</source>
      <translation>Para la tabla:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="364"/>
      <source>Unique:</source>
      <translation>Único:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="365"/>
      <source>Yes</source>
      <translation>Sí</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="365"/>
      <source>No</source>
      <translation>No</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="371"/>
      <source>Column</source>
      <translation>Columna</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="372"/>
      <source>Collating</source>
      <translation>Cotejamiento</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="373"/>
      <source>Sort order</source>
      <translation>Ordenar por</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="407"/>
      <source>Trigger: %1</source>
      <translation>Disparador: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="413"/>
      <source>Activated:</source>
      <translation>Activado:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="421"/>
      <source>Action:</source>
      <translation>Acción:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="428"/>
      <source>On view:</source>
      <translation>En la vista:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="430"/>
      <source>On table:</source>
      <translation>En la tabla:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="441"/>
      <source>Activate condition:</source>
      <translation>Condición de activación:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="448"/>
      <source>Code executed:</source>
      <translation>Código ejecutado:</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="486"/>
      <source>View: %1</source>
      <translation>Vista: %1</translation>
    </message>
    <message>
      <location filename="../htmlexport.cpp" line="565"/>
      <source>Document generated by Letos v%1 on %2</source>
      <translation>Documento generado por Letos v%1 el %2</translation>
    </message>
  </context>
  <context>
    <name>HtmlExportConfig</name>
    <message>
      <location filename="../htmlexport.ui" line="136"/>
      <source>Maximum number of characters per cell:</source>
      <translation>Número máximo de caracteres por celda:</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="182"/>
      <source>Include data types in first row</source>
      <translation>Incluir tipos de dato en la primera fila</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="143"/>
      <source>Column names as first row</source>
      <translation>Nombres de columna como la primera fila</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="126"/>
      <source>Row numbers as first column</source>
      <translation>Números de fila como la primera columna</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="91"/>
      <source>Output format</source>
      <translation>Formato de salida</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="20"/>
      <source>Custom header</source>
      <translation>Encabezado personalizado</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="26"/>
      <source>No custom header</source>
      <translation>Sin encabezado personalizado</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="39"/>
      <source>Define custom header content</source>
      <translation>Definir contenido del encabezado personalizado</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="52"/>
      <location filename="../htmlexport.ui" line="224"/>
      <source>HTML content</source>
      <translation>Contenido HTML</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="62"/>
      <source>Define custom header file</source>
      <translation>Definir archivo de encabezado personalizado</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="78"/>
      <source>Choose file for the header</source>
      <translation>Elegir archivo para el encabezado</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="81"/>
      <location filename="../htmlexport.ui" line="253"/>
      <source>HTML files (*.htm, *.html);;Text files (*.txt);;All files (*)</source>
      <translation>Archivos HTML (*.htm, *.html);;Archivos de texto (*.txt);;Todos los archivos (*)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="97"/>
      <source>Format document (new lines, indentation)</source>
      <translation>Formatear documento (nuevas líneas, indentación)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="110"/>
      <source>Compress (everything in one line)</source>
      <translation>Comprimir (todo en una sola línea)</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="153"/>
      <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
      <translation>&lt;p&gt;Cuando se activa, caracteres HTML como &amp;lt;, &amp;gt; y &amp; no son escapados en los valores exportados. Esto te permite por ejemplo, exportar documentos con hiper-vínculos funcionales, pero también podría resultar en un documento HTML incorrecto (pares no relacionados de caracteres &amp;lt; y &amp;gt;). Está advertido.&lt;/p&gt;</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="156"/>
      <source>Don&apos;t escape HTML characters</source>
      <translation>No escapar caracteres HTML</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="192"/>
      <source>Custom footer</source>
      <translation>Pie de página personalizado</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="198"/>
      <source>No custom footer</source>
      <translation>Sin pie de página personalizado</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="211"/>
      <source>Define custom footer content</source>
      <translation>Definir contenido del pie de página personalizado</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="234"/>
      <source>Define custom footer file</source>
      <translation>Definir archivo de pie de página personalizado</translation>
    </message>
    <message>
      <location filename="../htmlexport.ui" line="250"/>
      <source>Choose file for the footer</source>
      <translation>Elegir archivo para el pie de página</translation>
    </message>
  </context>
</TS>
